title:             Eliehoenai
email:             eliehoenai.84@gmail.com
description:       To Yahweh are mine eyes
author:            Eliehoenai
baseurl:           "/"
url:               "https://eliehoenai.github.io"

# Social Profiles
#twitter_username:  anything
#github_username:   anything
#facebook_username: anything

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
